language: php

php:
  - 7.2

services:
  - mysql

addons:
  apt:
    packages:
      - mysql-server-5.7

dist: bionic

sudo: required

script:
  - cp -r ./system/examples/mvc ./application && php ./application/test.php && rm -r ./application
  - cp -r ./system/examples/session ./application && php ./application/test.php && rm -r ./application
  - cp -r ./system/examples/mail ./application && php ./application/test.php && rm -r ./application
