language: php

php:
  - 7.2

services:
  - mysql

addons:
  apt:
    packages:
      - mysql-server-5.7

dist: bionic

sudo: required

script:
  - php ./system/scripts/test.php system/examples/mvc
  - php ./system/scripts/test.php system/examples/session
  - php ./system/scripts/test.php system/examples/mail
