language: php

php:
  - 7.2

services:
  - mysql

addons:
  apt:
    sources:
      - mysql-5.7
    packages:
      - mysql-server

dist: bionic

sudo: required

script:
  - cp -r ./system/examples/mvc application && php ./application/test.php
