<div class="container jumbotron">
  <h1>Welcome to pieni!</h1>
  <p>The page you are looking at is being generated by pieni.</p>
  <p>If you would like to customize this page, copy <code>views/welcome/index.php</code> from <code>./system/</code> to <code>./application/</code>.</p>
  <p>If you are exploring pieni for the very first time, you should start by reading the <a target="_blank" href="https://pieni.org/">User Guide</a>.</p>
  <p>To better understand, copy the following examples as <code>./application/</code> and run them all in order.</p>
  <ol>
    <li><code>./system/examples/mvc/</code></li>
    <li><code>./system/examples/session/</code></li>
    <li><code>./system/examples/mail/</code></li>
  </ol>
</div>
