<div class="container jumbotron">
  <h1>Welcome to pieni!</h1>
  <p>The page you are looking at is being generated by pieni.</p>
  <p>If you would like to customize this page, copy <code>views/welcome/index.php</code> from <code>./system/</code> to <code>./application/</code>.</p>
  <p>If you are exploring pieni for the very first time, you should start by reading the <a target="_blank" href="https://pieni.org/">User Guide</a>.</p>
  <p>To better understand the request flow, copy <code>./system/examples/mvc/</code> from </code> as <code>./application/</code>.</p>
</div>
